### ISSUE TITLE
ID not available <id> error

### ISSUE THREAD

**Issue by dunkensh** [seri/gettc#14]
When I try gettc some_id, it says "download problem to raw html ... id not available <id>.
I did put correct values in .gettc/config.yml file.

**Comment by seri** [comment]
Do you have this problem with all IDs? What happens when you run `gettc 11127`?

**Comment by dunkensh** [comment]
gettc 11127 works fine.

**Comment by seri** [comment]
Then you'll have to tell me which ID got you the problem.

**Comment by dunkensh** [comment]
http://community.topcoder.com/longcontest/?module=ViewProblemStatement&rd=16275&compid=45755

I tried both params

**Comment by seri** [comment]
Ah, gettc only supports the SRM, not marathon matches. I'm not active on Topcoder recently. Are these marathon matches cooler than SRM?

**Comment by dunkensh** [comment]
Matches are cool :)  It would be nice gettc to have support for them too.

**Comment by seri** [comment]
In my todo list. Stay tuned :)

**Comment by seri** [comment]
To everyone who requests support for Marathon Matches: 

Because of the irregular way that input and output data are presented in the problem statement for Marathon Matches, I don't see a way to consistently extract this information. Therefore, support for Marathon Matches will not be implemented, at least before there are structural changes from TopCoder.

By the way, you can still do this `gettc 13662` and the solution files can compile, but there are just no input/output data to test.
